server:
  port: 8081
spring:
  profiles:
    active: prod
---
server:
  port: 8083
spring:
  profiles: dev
---
server:
  port: 80
spring:
  profiles: prod
#
#
#
#person:
#    lastName: zhangsan
#    age: 18
#    boss: false
#    birth: 2017/12/12
#    maps: {k1: v1,k2: 12}
#    lists:
#      - lisi
#      - wangwu
#      - zhaoliu
#    dog:
#      name: 小狗
#      age: 2
